steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/rebateton-media-upload:$REVISION_ID", "."]

  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/rebateton-media-upload:$REVISION_ID"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'compute', 'ssh', 'tuannguyen@rebateton-dev-master', '--zone=us-central1-c',
      '--command=sudo su && docker pull gcr.io/$PROJECT_ID/rebateton-media-upload:$REVISION_ID && docker service update --image gcr.io/$PROJECT_ID/rebateton-media-upload:$REVISION_ID --with-registry-auth rebateton_media_upload'
    ]
